[project]
name = "stego-side-wing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["flask[async]>=3.1.2", "langdetect>=1.0.9"]
